language: minimal

sudo: false

dist: trusty

git:
  submodules: false

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work
  timeout: 300

addons:
  apt:
    packages:
    - python
    - python-numpy
    - libgmp-dev

# The order in which stages are run.
stages:
  - deps
  - compiler
  - tests

# The defaults that are apparently included by all jobs.
before_install:
  - ./.travis-setup.sh
  - export PATH=$HOME/.local/bin:$PATH

# We test against different Stackage snapshots.
jobs:
  include:
    - &deps
      stage: deps
      env: BUILD=stack STACK_YAML=stack.yaml
      script:
        - stack build --fast alex happy
        - stack --no-terminal test --fast --only-dependencies -j 3

    - <<: *deps
      env: BUILD=stack STACK_YAML=stack-lts-10.0.yaml
    - <<: *deps
      env: BUILD=stack STACK_YAML=stack-lts-9.2.yaml

    - &compiler
      stage: compiler
      env: BUILD=stack STACK_YAML=stack.yaml
      script:
        - travis_wait stack --no-terminal test -j 1 --fast

    - <<: *compiler
      env: BUILD=stack STACK_YAML=stack-lts-10.0.yaml
    - <<: *compiler
      env: BUILD=stack STACK_YAML=stack-lts-9.2.yaml

    # Note - this stage is only run for one version of GHC.
    - stage: tests
      env: BUILD=stack STACK_YAML=stack.yaml
      script:
        - stack install

        # Run integration test suite.
        - futhark-test --nobuffer tests examples
        - (cd pkgtests; ./test.sh)

        # Check for style issues.
        - stack install hlint --fast
        - tools/style-check.sh src

# EOF
