language: haskell

before_install:
  cabal install happy alex hlint

ghc: 7.8

script:
  - cabal configure --enable-tests && cabal build --ghc-options -Werror && cabal test
  - tools/style-check.sh src

notifications:
  email:
    - athas@sigkill.dk
    - cosmin.oancea@diku.dk
