language: haskell

before_install:
  cabal install happy alex

ghc: 7.8

script:
  - cabal configure --enable-tests && cabal build && cabal test
  - tools/style-check.sh src

notifications:
  email:
    - athas@sigkill.dk
    - cosmin.oancea@diku.dk
