# This is a simple Azure configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/azure_ci/

pool:
  vmImage: ubuntu-16.04

steps:
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack
- script: |
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies
- script: |
    # Build the package, its tests, and its docs and run the tests
    stack test --no-terminal --haddock --no-haddock-deps
  displayName: Run unit tests
- script: |
    stack exec -- futhark test --no-terminal tests examples
  displayName: Run integration tests
