resolver: nightly-2022-01-14
packages:
- .

flags: {}

extra-package-dbs: []

nix:
    packages: [zlib.dev, zlib.out, pkgconfig, z3]

# By default, stack doesn't compile multiple modules in parallel.
# This makes it do so.
ghc-options:
  $locals: -j -optP-Wno-nonportable-include-path

extra-deps:
- futhark-data-1.0.3.0
- futhark-server-1.1.2.0
- futhark-manifest-1.0.0.0
- aeson-2.0.1.0
- git: https://github.com/Munksgaard/haskell-z3.git
  commit: 23f6eebe199c292c8d556c52a245e64d4b3caa92
