flags: {}
setup-info:
  ghc:
    windows64:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-unknown-mingw32.tar.xz
        sha1: bdede26c1a2cfcf4ebb08329853d285e32213b3d
        content-length: 175053796
    linux64:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-deb8-linux.tar.xz
        sha1: 3e52527de6f1cad6d7f1c392ddde8148116d4e36
        content-length: 126809836
    macosx:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-apple-darwin.tar.xz
        sha1: 101405b4fef87a44adf34e48bb63a1a4e945c5c9
        content-length: 114088292
extra-deps:
- HUnit-1.6.0.0
- ListLike-4.5.1
- QuickCheck-2.10.0.1
- StateVar-1.1.0.4
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.7.3
- base-compat-0.9.3
- base-orphans-0.6
- base-prelude-1.2.0.1
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- call-stack-0.1.0
- comonad-5.0.1
- contravariant-1.4
- cpphs-1.20.8
- data-binary-ieee754-0.4.4
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- directory-tree-0.12.1
- distributive-0.5.2
- dlist-0.8.0.3
- exception-mtl-0.4.0.1
- exception-transformers-0.4.0.5
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- file-embed-0.0.10
- fmlist-0.9
- generic-deriving-1.11.2
- gitrev-1.3.1
- hashable-1.2.6.1
- haskell-src-exts-1.19.1
- haskell-src-meta-0.8.0.1
- hostname-1.0
- json-0.9.1
- language-c-quote-0.12
- mainland-pretty-0.6.1
- mtl-2.2.1
- neat-interpolation-0.3.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.1
- parsec-3.1.11
- polyparse-1.12
- primitive-0.6.2.0
- process-extras-0.7.2
- random-1.1
- raw-strings-qq-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- regex-tdfa-1.2.2
- safe-0.3.15
- semigroups-0.18.3
- srcloc-0.5.1.1
- stm-2.4.4.1
- syb-0.7
- symbol-0.2.4
- tagged-0.8.5
- temporary-1.2.1
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- test-framework-quickcheck2-0.3.0.4
- text-1.2.2.2
- tf-random-0.5
- th-expand-syns-0.4.3.0
- th-lift-0.7.7
- th-lift-instances-0.1.11
- th-orphans-0.13.3
- th-reify-many-0.1.7
- transformers-compat-0.5.1.4
- utf8-string-1.0.1.1
- vector-0.12.0.1
- vector-binary-instances-0.2.3.5
- void-0.7.2
- xml-1.3.14
- cabal-doctest-1.0.2
compiler-check: match-exact
compiler: ghc-8.2.1
resolver: ghc-8.2.1
