flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- ListLike-4.2.1
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- base-prelude-0.1.21
- constraints-0.4.1.3
- cpphs-1.20.1
- dlist-0.7.1.2
- equational-reasoning-0.2.0.7
- exception-mtl-0.4
- exception-transformers-0.4.0.3
- exceptions-0.8.2.1
- extensible-exceptions-0.1.1.4
- file-embed-0.0.9.1
- fmlist-0.9
- generic-deriving-1.10.4
- hashable-1.2.4.0
- haskell-src-exts-1.17.1
- haskell-src-meta-0.6.0.13
- hostname-1.0
- language-c-quote-0.11.4.1
- mainland-pretty-0.4.1.2
- monomorphic-0.0.3.3
- mtl-2.2.1
- neat-interpolation-0.2.3
- newtype-0.2
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- polyparse-1.11
- primitive-0.6.1.0
- process-extras-0.3.3.8
- random-1.1
- raw-strings-qq-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- regex-tdfa-1.2.1
- safe-0.3.9
- semigroups-0.18.1
- singletons-2.0.1
- sized-vector-1.4.3.0
- srcloc-0.5.1.0
- stm-2.4.4.1
- syb-0.6
- symbol-0.2.4
- tagged-0.8.3
- temporary-1.2.0.4
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- test-framework-quickcheck2-0.3.0.3
- text-1.2.2.0
- tf-random-0.5
- th-desugar-1.5.5
- th-expand-syns-0.3.0.6
- th-lift-0.7.6
- th-orphans-0.13.0
- th-reify-many-0.1.4
- transformers-compat-0.5.1.4
- type-natural-0.3.0.0
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- void-0.7.1
- xml-1.3.14
resolver: ghc-7.10.2
